version: '3.3'
services:
  bot:
    container_name: support-bot
    build: .
    restart: always
    ports:
      - "7772:7772"
    env_file:
      - ./.env
  postgres:
    container_name: support-bot-db
    image: postgres:14.0-alpine
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data/
    env_file:
      - ./.env